export default {
  avatar_url: "https://avatars.githubusercontent.com/u/48856495?v=4",
  bio: "Fresh graduate from Gazi University.\r\nCurrently improving my skills in React.",
  blog: "https://dribbble.com/cbsanal",
  company: null,
  created_at: "2019-03-23T10:52:03Z",
  email: null,
  events_url: "https://api.github.com/users/cbsanal/events{/privacy}",
  followers: 26,
  followers_url: "https://api.github.com/users/cbsanal/followers",
  following: 32,
  following_url: "https://api.github.com/users/cbsanal/following{/other_user}",
  gists_url: "https://api.github.com/users/cbsanal/gists{/gist_id}",
  gravatar_id: "",
  hireable: null,
  html_url: "https://github.com/cbsanal",
  id: 48856495,
  location: "Ankara, Turkey",
  login: "cbsanal",
  name: "Can Berk Sanal",
  node_id: "MDQ6VXNlcjQ4ODU2NDk1",
  organizations_url: "https://api.github.com/users/cbsanal/orgs",
  public_gists: 0,
  public_repos: 15,
  received_events_url: "https://api.github.com/users/cbsanal/received_events",
  repos_url: "https://api.github.com/users/cbsanal/repos",
  site_admin: false,
  starred_url: "https://api.github.com/users/cbsanal/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/cbsanal/subscriptions",
  twitter_username: null,
  type: "User",
  updated_at: "2021-10-24T17:10:34Z",
  url: "https://api.github.com/users/cbsanal",
};
