export default [
  {
    avatar_url: "https://avatars.githubusercontent.com/u/25546221?v=4",
    events_url: "https://api.github.com/users/ebubekirrzgr/events{/privacy}",
    followers_url: "https://api.github.com/users/ebubekirrzgr/followers",
    following_url:
      "https://api.github.com/users/ebubekirrzgr/following{/other_user}",
    gists_url: "https://api.github.com/users/ebubekirrzgr/gists{/gist_id}",
    gravatar_id: "",
    html_url: "https://github.com/ebubekirrzgr",
    id: 25546221,
    login: "ebubekirrzgr",
    node_id: "MDQ6VXNlcjI1NTQ2MjIx",
    organizations_url: "https://api.github.com/users/ebubekirrzgr/orgs",
    received_events_url:
      "https://api.github.com/users/ebubekirrzgr/received_events",
    repos_url: "https://api.github.com/users/ebubekirrzgr/repos",
    site_admin: false,
    starred_url:
      "https://api.github.com/users/ebubekirrzgr/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/ebubekirrzgr/subscriptions",
    type: "User",
    url: "https://api.github.com/users/ebubekirrzgr",
  },
  {
    avatar_url: "https://avatars.githubusercontent.com/u/30556140?v=4",
    events_url: "https://api.github.com/users/ialiayd/events{/privacy}",
    followers_url: "https://api.github.com/users/ialiayd/followers",
    following_url:
      "https://api.github.com/users/ialiayd/following{/other_user}",
    gists_url: "https://api.github.com/users/ialiayd/gists{/gist_id}",
    gravatar_id: "",
    html_url: "https://github.com/ialiayd",
    id: 30556140,
    login: "ialiayd",
    node_id: "MDQ6VXNlcjMwNTU2MTQw",
    organizations_url: "https://api.github.com/users/ialiayd/orgs",
    received_events_url: "https://api.github.com/users/ialiayd/received_events",
    repos_url: "https://api.github.com/users/ialiayd/repos",
    site_admin: false,
    starred_url: "https://api.github.com/users/ialiayd/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ialiayd/subscriptions",
    type: "User",
    url: "https://api.github.com/users/ialiayd",
  },
  {
    avatar_url: "https://avatars.githubusercontent.com/u/34400358?v=4",
    events_url: "https://api.github.com/users/AysegulTopyurek/events{/privacy}",
    followers_url: "https://api.github.com/users/AysegulTopyurek/followers",
    following_url:
      "https://api.github.com/users/AysegulTopyurek/following{/other_user}",
    gists_url: "https://api.github.com/users/AysegulTopyurek/gists{/gist_id}",
    gravatar_id: "",
    html_url: "https://github.com/AysegulTopyurek",
    id: 34400358,
    login: "AysegulTopyurek",
    node_id: "MDQ6VXNlcjM0NDAwMzU4",
    organizations_url: "https://api.github.com/users/AysegulTopyurek/orgs",
    received_events_url:
      "https://api.github.com/users/AysegulTopyurek/received_events",
    repos_url: "https://api.github.com/users/AysegulTopyurek/repos",
    site_admin: false,
    starred_url:
      "https://api.github.com/users/AysegulTopyurek/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/AysegulTopyurek/subscriptions",
    type: "User",
    url: "https://api.github.com/users/AysegulTopyurek",
  },
  {
    avatar_url: "https://avatars.githubusercontent.com/u/36002989?v=4",
    events_url: "https://api.github.com/users/akin-elmas/events{/privacy}",
    followers_url: "https://api.github.com/users/akin-elmas/followers",
    following_url:
      "https://api.github.com/users/akin-elmas/following{/other_user}",
    gists_url: "https://api.github.com/users/akin-elmas/gists{/gist_id}",
    gravatar_id: "",
    html_url: "https://github.com/akin-elmas",
    id: 36002989,
    login: "akin-elmas",
    node_id: "MDQ6VXNlcjM2MDAyOTg5",
    organizations_url: "https://api.github.com/users/akin-elmas/orgs",
    received_events_url:
      "https://api.github.com/users/akin-elmas/received_events",
    repos_url: "https://api.github.com/users/akin-elmas/repos",
    site_admin: false,
    starred_url:
      "https://api.github.com/users/akin-elmas/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/akin-elmas/subscriptions",
    type: "User",
    url: "https://api.github.com/users/akin-elmas",
  },
  {
    avatar_url: "https://avatars.githubusercontent.com/u/41874858?v=4",
    events_url: "https://api.github.com/users/ercumentlacin/events{/privacy}",
    followers_url: "https://api.github.com/users/ercumentlacin/followers",
    following_url:
      "https://api.github.com/users/ercumentlacin/following{/other_user}",
    gists_url: "https://api.github.com/users/ercumentlacin/gists{/gist_id}",
    gravatar_id: "",
    html_url: "https://github.com/ercumentlacin",
    id: 41874858,
    login: "ercumentlacin",
    node_id: "MDQ6VXNlcjQxODc0ODU4",
    organizations_url: "https://api.github.com/users/ercumentlacin/orgs",
    received_events_url:
      "https://api.github.com/users/ercumentlacin/received_events",
    repos_url: "https://api.github.com/users/ercumentlacin/repos",
    site_admin: false,
    starred_url:
      "https://api.github.com/users/ercumentlacin/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/ercumentlacin/subscriptions",
    type: "User",
    url: "https://api.github.com/users/ercumentlacin",
  },
  {
    avatar_url: "https://avatars.githubusercontent.com/u/44754934?v=4",
    events_url: "https://api.github.com/users/MuratAkbaba006/events{/privacy}",
    followers_url: "https://api.github.com/users/MuratAkbaba006/followers",
    following_url:
      "https://api.github.com/users/MuratAkbaba006/following{/other_user}",
    gists_url: "https://api.github.com/users/MuratAkbaba006/gists{/gist_id}",
    gravatar_id: "",
    html_url: "https://github.com/MuratAkbaba006",
    id: 44754934,
    login: "MuratAkbaba006",
    node_id: "MDQ6VXNlcjQ0NzU0OTM0",
    organizations_url: "https://api.github.com/users/MuratAkbaba006/orgs",
    received_events_url:
      "https://api.github.com/users/MuratAkbaba006/received_events",
    repos_url: "https://api.github.com/users/MuratAkbaba006/repos",
    site_admin: false,
    starred_url:
      "https://api.github.com/users/MuratAkbaba006/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/MuratAkbaba006/subscriptions",
    type: "User",
    url: "https://api.github.com/users/MuratAkbaba006",
  },
  {
    avatar_url: "https://avatars.githubusercontent.com/u/45014544?v=4",
    events_url: "https://api.github.com/users/mervemetinoglu/events{/privacy}",
    followers_url: "https://api.github.com/users/mervemetinoglu/followers",
    following_url:
      "https://api.github.com/users/mervemetinoglu/following{/other_user}",
    gists_url: "https://api.github.com/users/mervemetinoglu/gists{/gist_id}",
    gravatar_id: "",
    html_url: "https://github.com/mervemetinoglu",
    id: 45014544,
    login: "mervemetinoglu",
    node_id: "MDQ6VXNlcjQ1MDE0NTQ0",
    organizations_url: "https://api.github.com/users/mervemetinoglu/orgs",
    received_events_url:
      "https://api.github.com/users/mervemetinoglu/received_events",
    repos_url: "https://api.github.com/users/mervemetinoglu/repos",
    site_admin: false,
    starred_url:
      "https://api.github.com/users/mervemetinoglu/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/mervemetinoglu/subscriptions",
    type: "User",
    url: "https://api.github.com/users/mervemetinoglu",
  },
  {
    avatar_url: "https://avatars.githubusercontent.com/u/46095641?v=4",
    events_url: "https://api.github.com/users/gurh4nn/events{/privacy}",
    followers_url: "https://api.github.com/users/gurh4nn/followers",
    following_url:
      "https://api.github.com/users/gurh4nn/following{/other_user}",
    gists_url: "https://api.github.com/users/gurh4nn/gists{/gist_id}",
    gravatar_id: "",
    html_url: "https://github.com/gurh4nn",
    id: 46095641,
    login: "gurh4nn",
    node_id: "MDQ6VXNlcjQ2MDk1NjQx",
    organizations_url: "https://api.github.com/users/gurh4nn/orgs",
    received_events_url: "https://api.github.com/users/gurh4nn/received_events",
    repos_url: "https://api.github.com/users/gurh4nn/repos",
    site_admin: false,
    starred_url: "https://api.github.com/users/gurh4nn/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/gurh4nn/subscriptions",
    type: "User",
    url: "https://api.github.com/users/gurh4nn",
  },
  {
    avatar_url: "https://avatars.githubusercontent.com/u/56076939?v=4",
    events_url: "https://api.github.com/users/busra-yildirim/events{/privacy}",
    followers_url: "https://api.github.com/users/busra-yildirim/followers",
    following_url:
      "https://api.github.com/users/busra-yildirim/following{/other_user}",
    gists_url: "https://api.github.com/users/busra-yildirim/gists{/gist_id}",
    gravatar_id: "",
    html_url: "https://github.com/busra-yildirim",
    id: 56076939,
    login: "busra-yildirim",
    node_id: "MDQ6VXNlcjU2MDc2OTM5",
    organizations_url: "https://api.github.com/users/busra-yildirim/orgs",
    received_events_url:
      "https://api.github.com/users/busra-yildirim/received_events",
    repos_url: "https://api.github.com/users/busra-yildirim/repos",
    site_admin: false,
    starred_url:
      "https://api.github.com/users/busra-yildirim/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/busra-yildirim/subscriptions",
    type: "User",
    url: "https://api.github.com/users/busra-yildirim",
  },
  {
    avatar_url: "https://avatars.githubusercontent.com/u/56235622?v=4",
    events_url: "https://api.github.com/users/ooguzyuksel/events{/privacy}",
    followers_url: "https://api.github.com/users/ooguzyuksel/followers",
    following_url:
      "https://api.github.com/users/ooguzyuksel/following{/other_user}",
    gists_url: "https://api.github.com/users/ooguzyuksel/gists{/gist_id}",
    gravatar_id: "",
    html_url: "https://github.com/ooguzyuksel",
    id: 56235622,
    login: "ooguzyuksel",
    node_id: "MDQ6VXNlcjU2MjM1NjIy",
    organizations_url: "https://api.github.com/users/ooguzyuksel/orgs",
    received_events_url:
      "https://api.github.com/users/ooguzyuksel/received_events",
    repos_url: "https://api.github.com/users/ooguzyuksel/repos",
    site_admin: false,
    starred_url:
      "https://api.github.com/users/ooguzyuksel/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ooguzyuksel/subscriptions",
    type: "User",
    url: "https://api.github.com/users/ooguzyuksel",
  },
  {
    avatar_url: "https://avatars.githubusercontent.com/u/56415572?v=4",
    events_url: "https://api.github.com/users/cllcnkrt/events{/privacy}",
    followers_url: "https://api.github.com/users/cllcnkrt/followers",
    following_url:
      "https://api.github.com/users/cllcnkrt/following{/other_user}",
    gists_url: "https://api.github.com/users/cllcnkrt/gists{/gist_id}",
    gravatar_id: "",
    html_url: "https://github.com/cllcnkrt",
    id: 56415572,
    login: "cllcnkrt",
    node_id: "MDQ6VXNlcjU2NDE1NTcy",
    organizations_url: "https://api.github.com/users/cllcnkrt/orgs",
    received_events_url:
      "https://api.github.com/users/cllcnkrt/received_events",
    repos_url: "https://api.github.com/users/cllcnkrt/repos",
    site_admin: false,
    starred_url: "https://api.github.com/users/cllcnkrt/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/cllcnkrt/subscriptions",
    type: "User",
    url: "https://api.github.com/users/cllcnkrt",
  },
  {
    avatar_url: "https://avatars.githubusercontent.com/u/56503078?v=4",
    events_url: "https://api.github.com/users/ouzhan-uysal/events{/privacy}",
    followers_url: "https://api.github.com/users/ouzhan-uysal/followers",
    following_url:
      "https://api.github.com/users/ouzhan-uysal/following{/other_user}",
    gists_url: "https://api.github.com/users/ouzhan-uysal/gists{/gist_id}",
    gravatar_id: "",
    html_url: "https://github.com/ouzhan-uysal",
    id: 56503078,
    login: "ouzhan-uysal",
    node_id: "MDQ6VXNlcjU2NTAzMDc4",
    organizations_url: "https://api.github.com/users/ouzhan-uysal/orgs",
    received_events_url:
      "https://api.github.com/users/ouzhan-uysal/received_events",
    repos_url: "https://api.github.com/users/ouzhan-uysal/repos",
    site_admin: false,
    starred_url:
      "https://api.github.com/users/ouzhan-uysal/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/ouzhan-uysal/subscriptions",
    type: "User",
    url: "https://api.github.com/users/ouzhan-uysal",
  },
  {
    avatar_url: "https://avatars.githubusercontent.com/u/60944453?v=4",
    events_url: "https://api.github.com/users/OzerOzturk/events{/privacy}",
    followers_url: "https://api.github.com/users/OzerOzturk/followers",
    following_url:
      "https://api.github.com/users/OzerOzturk/following{/other_user}",
    gists_url: "https://api.github.com/users/OzerOzturk/gists{/gist_id}",
    gravatar_id: "",
    html_url: "https://github.com/OzerOzturk",
    id: 60944453,
    login: "OzerOzturk",
    node_id: "MDQ6VXNlcjYwOTQ0NDUz",
    organizations_url: "https://api.github.com/users/OzerOzturk/orgs",
    received_events_url:
      "https://api.github.com/users/OzerOzturk/received_events",
    repos_url: "https://api.github.com/users/OzerOzturk/repos",
    site_admin: false,
    starred_url:
      "https://api.github.com/users/OzerOzturk/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/OzerOzturk/subscriptions",
    type: "User",
    url: "https://api.github.com/users/OzerOzturk",
  },
  {
    avatar_url: "https://avatars.githubusercontent.com/u/62357472?v=4",
    events_url: "https://api.github.com/users/murat-atalik/events{/privacy}",
    followers_url: "https://api.github.com/users/murat-atalik/followers",
    following_url:
      "https://api.github.com/users/murat-atalik/following{/other_user}",
    gists_url: "https://api.github.com/users/murat-atalik/gists{/gist_id}",
    gravatar_id: "",
    html_url: "https://github.com/murat-atalik",
    id: 62357472,
    login: "murat-atalik",
    node_id: "MDQ6VXNlcjYyMzU3NDcy",
    organizations_url: "https://api.github.com/users/murat-atalik/orgs",
    received_events_url:
      "https://api.github.com/users/murat-atalik/received_events",
    repos_url: "https://api.github.com/users/murat-atalik/repos",
    site_admin: false,
    starred_url:
      "https://api.github.com/users/murat-atalik/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/murat-atalik/subscriptions",
    type: "User",
    url: "https://api.github.com/users/murat-atalik",
  },
  {
    avatar_url: "https://avatars.githubusercontent.com/u/62360515?v=4",
    events_url: "https://api.github.com/users/furkancetkin/events{/privacy}",
    followers_url: "https://api.github.com/users/furkancetkin/followers",
    following_url:
      "https://api.github.com/users/furkancetkin/following{/other_user}",
    gists_url: "https://api.github.com/users/furkancetkin/gists{/gist_id}",
    gravatar_id: "",
    html_url: "https://github.com/furkancetkin",
    id: 62360515,
    login: "furkancetkin",
    node_id: "MDQ6VXNlcjYyMzYwNTE1",
    organizations_url: "https://api.github.com/users/furkancetkin/orgs",
    received_events_url:
      "https://api.github.com/users/furkancetkin/received_events",
    repos_url: "https://api.github.com/users/furkancetkin/repos",
    site_admin: false,
    starred_url:
      "https://api.github.com/users/furkancetkin/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/furkancetkin/subscriptions",
    type: "User",
    url: "https://api.github.com/users/furkancetkin",
  },
  {
    avatar_url: "https://avatars.githubusercontent.com/u/65915453?v=4",
    events_url: "https://api.github.com/users/serkanc7/events{/privacy}",
    followers_url: "https://api.github.com/users/serkanc7/followers",
    following_url:
      "https://api.github.com/users/serkanc7/following{/other_user}",
    gists_url: "https://api.github.com/users/serkanc7/gists{/gist_id}",
    gravatar_id: "",
    html_url: "https://github.com/serkanc7",
    id: 65915453,
    login: "serkanc7",
    node_id: "MDQ6VXNlcjY1OTE1NDUz",
    organizations_url: "https://api.github.com/users/serkanc7/orgs",
    received_events_url:
      "https://api.github.com/users/serkanc7/received_events",
    repos_url: "https://api.github.com/users/serkanc7/repos",
    site_admin: false,
    starred_url: "https://api.github.com/users/serkanc7/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/serkanc7/subscriptions",
    type: "User",
    url: "https://api.github.com/users/serkanc7",
  },
  {
    avatar_url: "https://avatars.githubusercontent.com/u/70916991?v=4",
    events_url: "https://api.github.com/users/YoncaYeprem/events{/privacy}",
    followers_url: "https://api.github.com/users/YoncaYeprem/followers",
    following_url:
      "https://api.github.com/users/YoncaYeprem/following{/other_user}",
    gists_url: "https://api.github.com/users/YoncaYeprem/gists{/gist_id}",
    gravatar_id: "",
    html_url: "https://github.com/YoncaYeprem",
    id: 70916991,
    login: "YoncaYeprem",
    node_id: "MDQ6VXNlcjcwOTE2OTkx",
    organizations_url: "https://api.github.com/users/YoncaYeprem/orgs",
    received_events_url:
      "https://api.github.com/users/YoncaYeprem/received_events",
    repos_url: "https://api.github.com/users/YoncaYeprem/repos",
    site_admin: false,
    starred_url:
      "https://api.github.com/users/YoncaYeprem/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/YoncaYeprem/subscriptions",
    type: "User",
    url: "https://api.github.com/users/YoncaYeprem",
  },
  {
    avatar_url: "https://avatars.githubusercontent.com/u/71692992?v=4",
    events_url: "https://api.github.com/users/haguse/events{/privacy}",
    followers_url: "https://api.github.com/users/haguse/followers",
    following_url: "https://api.github.com/users/haguse/following{/other_user}",
    gists_url: "https://api.github.com/users/haguse/gists{/gist_id}",
    gravatar_id: "",
    html_url: "https://github.com/haguse",
    id: 71692992,
    login: "haguse",
    node_id: "MDQ6VXNlcjcxNjkyOTky",
    organizations_url: "https://api.github.com/users/haguse/orgs",
    received_events_url: "https://api.github.com/users/haguse/received_events",
    repos_url: "https://api.github.com/users/haguse/repos",
    site_admin: false,
    starred_url: "https://api.github.com/users/haguse/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/haguse/subscriptions",
    type: "User",
    url: "https://api.github.com/users/haguse",
  },
  {
    avatar_url: "https://avatars.githubusercontent.com/u/73859360?v=4",
    events_url:
      "https://api.github.com/users/ertugrulevrensel/events{/privacy}",
    followers_url: "https://api.github.com/users/ertugrulevrensel/followers",
    following_url:
      "https://api.github.com/users/ertugrulevrensel/following{/other_user}",
    gists_url: "https://api.github.com/users/ertugrulevrensel/gists{/gist_id}",
    gravatar_id: "",
    html_url: "https://github.com/ertugrulevrensel",
    id: 73859360,
    login: "ertugrulevrensel",
    node_id: "MDQ6VXNlcjczODU5MzYw",
    organizations_url: "https://api.github.com/users/ertugrulevrensel/orgs",
    received_events_url:
      "https://api.github.com/users/ertugrulevrensel/received_events",
    repos_url: "https://api.github.com/users/ertugrulevrensel/repos",
    site_admin: false,
    starred_url:
      "https://api.github.com/users/ertugrulevrensel/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/ertugrulevrensel/subscriptions",
    type: "User",
    url: "https://api.github.com/users/ertugrulevrensel",
  },
  {
    avatar_url: "https://avatars.githubusercontent.com/u/81320924?v=4",
    events_url: "https://api.github.com/users/yagizyldrm/events{/privacy}",
    followers_url: "https://api.github.com/users/yagizyldrm/followers",
    following_url:
      "https://api.github.com/users/yagizyldrm/following{/other_user}",
    gists_url: "https://api.github.com/users/yagizyldrm/gists{/gist_id}",
    gravatar_id: "",
    html_url: "https://github.com/yagizyldrm",
    id: 81320924,
    login: "yagizyldrm",
    node_id: "MDQ6VXNlcjgxMzIwOTI0",
    organizations_url: "https://api.github.com/users/yagizyldrm/orgs",
    received_events_url:
      "https://api.github.com/users/yagizyldrm/received_events",
    repos_url: "https://api.github.com/users/yagizyldrm/repos",
    site_admin: false,
    starred_url:
      "https://api.github.com/users/yagizyldrm/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/yagizyldrm/subscriptions",
    type: "User",
    url: "https://api.github.com/users/yagizyldrm",
  },
  {
    avatar_url: "https://avatars.githubusercontent.com/u/84075304?v=4",
    events_url: "https://api.github.com/users/rumica/events{/privacy}",
    followers_url: "https://api.github.com/users/rumica/followers",
    following_url: "https://api.github.com/users/rumica/following{/other_user}",
    gists_url: "https://api.github.com/users/rumica/gists{/gist_id}",
    gravatar_id: "",
    html_url: "https://github.com/rumica",
    id: 84075304,
    login: "rumica",
    node_id: "MDQ6VXNlcjg0MDc1MzA0",
    organizations_url: "https://api.github.com/users/rumica/orgs",
    received_events_url: "https://api.github.com/users/rumica/received_events",
    repos_url: "https://api.github.com/users/rumica/repos",
    site_admin: false,
    starred_url: "https://api.github.com/users/rumica/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/rumica/subscriptions",
    type: "User",
    url: "https://api.github.com/users/rumica",
  },
  {
    avatar_url: "https://avatars.githubusercontent.com/u/84291843?v=4",
    events_url: "https://api.github.com/users/SevalKu/events{/privacy}",
    followers_url: "https://api.github.com/users/SevalKu/followers",
    following_url:
      "https://api.github.com/users/SevalKu/following{/other_user}",
    gists_url: "https://api.github.com/users/SevalKu/gists{/gist_id}",
    gravatar_id: "",
    html_url: "https://github.com/SevalKu",
    id: 84291843,
    login: "SevalKu",
    node_id: "MDQ6VXNlcjg0MjkxODQz",
    organizations_url: "https://api.github.com/users/SevalKu/orgs",
    received_events_url: "https://api.github.com/users/SevalKu/received_events",
    repos_url: "https://api.github.com/users/SevalKu/repos",
    site_admin: false,
    starred_url: "https://api.github.com/users/SevalKu/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/SevalKu/subscriptions",
    type: "User",
    url: "https://api.github.com/users/SevalKu",
  },
  {
    avatar_url: "https://avatars.githubusercontent.com/u/85337758?v=4",
    events_url: "https://api.github.com/users/Ogzhnsfgl/events{/privacy}",
    followers_url: "https://api.github.com/users/Ogzhnsfgl/followers",
    following_url:
      "https://api.github.com/users/Ogzhnsfgl/following{/other_user}",
    gists_url: "https://api.github.com/users/Ogzhnsfgl/gists{/gist_id}",
    gravatar_id: "",
    html_url: "https://github.com/Ogzhnsfgl",
    id: 85337758,
    login: "Ogzhnsfgl",
    node_id: "MDQ6VXNlcjg1MzM3NzU4",
    organizations_url: "https://api.github.com/users/Ogzhnsfgl/orgs",
    received_events_url:
      "https://api.github.com/users/Ogzhnsfgl/received_events",
    repos_url: "https://api.github.com/users/Ogzhnsfgl/repos",
    site_admin: false,
    starred_url:
      "https://api.github.com/users/Ogzhnsfgl/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Ogzhnsfgl/subscriptions",
    type: "User",
    url: "https://api.github.com/users/Ogzhnsfgl",
  },
  {
    avatar_url: "https://avatars.githubusercontent.com/u/86553371?v=4",
    events_url: "https://api.github.com/users/Ozgenursaltik/events{/privacy}",
    followers_url: "https://api.github.com/users/Ozgenursaltik/followers",
    following_url:
      "https://api.github.com/users/Ozgenursaltik/following{/other_user}",
    gists_url: "https://api.github.com/users/Ozgenursaltik/gists{/gist_id}",
    gravatar_id: "",
    html_url: "https://github.com/Ozgenursaltik",
    id: 86553371,
    login: "Ozgenursaltik",
    node_id: "MDQ6VXNlcjg2NTUzMzcx",
    organizations_url: "https://api.github.com/users/Ozgenursaltik/orgs",
    received_events_url:
      "https://api.github.com/users/Ozgenursaltik/received_events",
    repos_url: "https://api.github.com/users/Ozgenursaltik/repos",
    site_admin: false,
    starred_url:
      "https://api.github.com/users/Ozgenursaltik/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/Ozgenursaltik/subscriptions",
    type: "User",
    url: "https://api.github.com/users/Ozgenursaltik",
  },
  {
    avatar_url: "https://avatars.githubusercontent.com/u/87365494?v=4",
    events_url: "https://api.github.com/users/dilakasap/events{/privacy}",
    followers_url: "https://api.github.com/users/dilakasap/followers",
    following_url:
      "https://api.github.com/users/dilakasap/following{/other_user}",
    gists_url: "https://api.github.com/users/dilakasap/gists{/gist_id}",
    gravatar_id: "",
    html_url: "https://github.com/dilakasap",
    id: 87365494,
    login: "dilakasap",
    node_id: "MDQ6VXNlcjg3MzY1NDk0",
    organizations_url: "https://api.github.com/users/dilakasap/orgs",
    received_events_url:
      "https://api.github.com/users/dilakasap/received_events",
    repos_url: "https://api.github.com/users/dilakasap/repos",
    site_admin: false,
    starred_url:
      "https://api.github.com/users/dilakasap/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/dilakasap/subscriptions",
    type: "User",
    url: "https://api.github.com/users/dilakasap",
  },
  {
    avatar_url: "https://avatars.githubusercontent.com/u/89779043?v=4",
    events_url: "https://api.github.com/users/ErmanEU/events{/privacy}",
    followers_url: "https://api.github.com/users/ErmanEU/followers",
    following_url:
      "https://api.github.com/users/ErmanEU/following{/other_user}",
    gists_url: "https://api.github.com/users/ErmanEU/gists{/gist_id}",
    gravatar_id: "",
    html_url: "https://github.com/ErmanEU",
    id: 89779043,
    login: "ErmanEU",
    node_id: "MDQ6VXNlcjg5Nzc5MDQz",
    organizations_url: "https://api.github.com/users/ErmanEU/orgs",
    received_events_url: "https://api.github.com/users/ErmanEU/received_events",
    repos_url: "https://api.github.com/users/ErmanEU/repos",
    site_admin: false,
    starred_url: "https://api.github.com/users/ErmanEU/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ErmanEU/subscriptions",
    type: "User",
    url: "https://api.github.com/users/ErmanEU",
  },
];
